version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - yachtpricer-net

  backend:
    build:
      context: ./backend
    command: npm run start:dev         # dev-watch режим
    working_dir: /app
    ports:
      - "8000:8000"
      - "5555:5555"                    # Prisma Studio
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/yachtpricer
    volumes:
      - ./backend:/app                 # исходники внутрь контейнера
      - backend_node_modules:/app/node_modules  # именованный volume
    depends_on:
      - db
    networks:
      - yachtpricer-net

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yachtpricer
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yachtpricer-net

networks:
  yachtpricer-net:
    driver: bridge

volumes:
  backend_node_modules: {}
  frontend_node_modules: {}