services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_URL: /api
      VITE_CLERK_PUBLISHABLE_KEY: "pk_test_ZXhjaXRpbmctbXVsZS0zMS5jbGVyay5hY2NvdW50cy5kZXYk"
    networks:
      - yachtpricer-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    working_dir: /app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/yachtpricer
      CORS_ORIGINS: https://sandbox.leonidk.de,http://localhost:3000,http://localhost:3001

      NAUSYS_USE_MOCK: "true"

      AUTH_MODE: clerk

      CLERK_SECRET_KEY: sk_test_b2GEuGwtyyfcZ27SAA4ZSGLBsihQ9E5ipVQ4q0ureQ
      CLERK_ISSUER: https://exciting-mule-31.clerk.accounts.dev

    depends_on:
      db:
        condition: service_healthy
    networks:
      - yachtpricer-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"require('http').get('http://localhost:8000/api/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yachtpricer
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yachtpricer"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - yachtpricer-net

  prisma-studio:
    profiles: ["tools"]
    image: node:20-alpine
    working_dir: /workspace/backend
    command: >
      sh -lc '
        npx -y prisma@6.14.0 studio
          --port 5555
          --browser none
          --schema=./prisma/schema.prisma
      '
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/yachtpricer
    volumes:
      - ./:/workspace:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yachtpricer-net
    ports:
      - "127.0.0.1:5557:5555"  # слушаем ТОЛЬКО на localhost VPS

networks:
  yachtpricer-net:
    driver: bridge