name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: sandbox.leonidk.de
          username: leonidk
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/yachtpricer/frontend
            git checkout main
            git pull origin main
            npm ci
            npm run build
            pm2 restart yachtpricer || pm2 serve dist 80 --spa --name yachtpricer