name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS (git pull + docker compose up)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: sandbox.leonidk.de
          username: leonidk
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail

            REPO_DIR=/home/leonidk/yachtpricer/yachtpricer-mvp
            ORIGIN=https://github.com/klb1963/yachtpricer-mvp.git

            # 0) Страховка: выставить владельца на текущего пользователя (борется с "Permission denied"/dubious ownership")
            mkdir -p "$REPO_DIR"
            chown -R "$USER":"$USER" "$REPO_DIR" || true

            # 1) Если репозиторий ещё не инициализирован — клонируем/инициализируем
            if [ ! -d "$REPO_DIR/.git" ]; then
              if [ -z "$(ls -A "$REPO_DIR")" ]; then
                git clone --depth=1 "$ORIGIN" "$REPO_DIR"
              else
                cd "$REPO_DIR"
                git init
                git remote add origin "$ORIGIN" || true
              fi
            fi

            cd "$REPO_DIR"

            # 2) Разрешаем git работать в этой папке (исправляет 'dubious ownership')
            git config --global --add safe.directory "$REPO_DIR"

            # 3) Обновляем код
            git fetch --all --prune
            git reset --hard origin/main

            # 4) Пересобираем и поднимаем контейнеры
            docker compose pull || true
            docker compose up -d --build

            # 5) Ждём, пока backend станет здоров
            for i in $(seq 1 30); do
              if curl -fsS http://localhost:8000/api/health >/dev/null; then
                echo "Backend is healthy."
                break
              fi
              echo "Waiting for backend... ($i/30)"
              sleep 2
            done

            # 6) Уборка (необязательно)
            docker system prune -f || true

            # 7) Показать статус
            docker compose ps