name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-vps
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - name: Checkout (no artifacts needed)
        uses: actions/checkout@v4

      - name: Deploy to VPS (git pull + docker compose up)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: sandbox.leonidk.de
          username: leonidk
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -euxo pipefail
            cd /home/leonidk/yachtpricer/yachtpricer-mvp

            # Обновляем код
            git fetch --all --prune
            git reset --hard origin/main

            # Пересобираем и поднимаем контейнеры
            docker compose pull || true
            docker compose up -d --build

            # Ждём, пока бэкенд станет здоров
            i=0
            until curl -fsS http://localhost:8000/api/health >/dev/null || [ $i -gt 30 ]; do
              i=$((i+1))
              sleep 2
            done

            docker compose ps
            docker system prune -f || true